AWSTemplateFormatVersion: '2010-09-09'
Description: Attach S3 upload notifications using a custom resource

Parameters:
  BucketName:
    Type: String
  LambdaArn:
    Type: String

Resources:
  S3NotificationConfiguratorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3NotificationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketNotification
                  - s3:PutBucketNotification
                Resource: !Sub arn:aws:s3:::${BucketName}
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  S3NotificationConfiguratorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt S3NotificationConfiguratorRole.Arn
      Timeout: 60
      Code:
        ZipFile: |
          import json
          import boto3
          import cfnresponse

          s3 = boto3.client("s3")

          def handler(event, context):
              try:
                  props = event["ResourceProperties"]
                  bucket = props["Bucket"]
                  function_arn = props["FunctionArn"]

                  if event["RequestType"] in ["Create", "Update"]:
                      s3.put_bucket_notification_configuration(
                          Bucket=bucket,
                          NotificationConfiguration={
                              "LambdaFunctionConfigurations": [
                                  {
                                      "LambdaFunctionArn": function_arn,
                                      "Events": ["s3:ObjectCreated:*"],
                                      "Filter": {
                                          "Key": {
                                              "FilterRules": [
                                                  {"Name": "suffix", "Value": ".jpg"}
                                              ]
                                          }
                                      },
                                  }
                              ]
                          },
                      )

                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                  cfnresponse.send(event, context, cfnresponse.FAILED, {"Error": str(e)})

  AllowS3InvokeIngest:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaArn
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${BucketName}

  ConfigureUploadBucketNotifications:
    Type: Custom::S3Notification
    DependsOn: AllowS3InvokeIngest
    Properties:
      ServiceToken: !GetAtt S3NotificationConfiguratorFunction.Arn
      Bucket: !Ref BucketName
      FunctionArn: !Ref LambdaArn

