AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Event-driven image processing pipeline (S3 -> Lambda -> SNS -> SQS -> Lambda)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:
  # -------------------------
  # Core buckets
  # -------------------------
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # -------------------------
  # Messaging (SNS -> SQS + DLQ)
  # -------------------------
  FanoutTopic:
    Type: AWS::SNS::Topic

  WorkerDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days

  WorkerQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt WorkerDLQ.Arn
        maxReceiveCount: 3

  TopicToQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref FanoutTopic
      Protocol: sqs
      Endpoint: !GetAtt WorkerQueue.Arn
      RawMessageDelivery: true

  AllowSnsToSendToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref WorkerQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSNSPublish
            Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt WorkerQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref FanoutTopic

  # -------------------------
  # Ingest Lambda (S3 -> SNS)
  # -------------------------
  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/ingest/
      Handler: app.lambda_handler
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FanoutTopic.TopicName
      Environment:
        Variables:
          TOPIC_ARN: !Ref FanoutTopic
          UPLOAD_BUCKET: !Ref UploadBucket

  # -------------------------
  # Worker Lambda (SQS -> S3)
  # -------------------------
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/worker/
      Handler: app.lambda_handler
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt WorkerQueue.QueueName
        - S3WritePolicy:
            BucketName: !Ref ProcessedBucket
      Environment:
        Variables:
          PROCESSED_BUCKET: !Ref ProcessedBucket
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt WorkerQueue.Arn
            BatchSize: 5

  # -------------------------
  # Custom Resource Lambda (Configurator)
  # Configures S3 notification AFTER resources exist
  # -------------------------
  S3NotificationConfiguratorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3NotificationConfiguratorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketNotificationConfiguration
                  - s3:GetBucketNotificationConfiguration
                Resource: "*"
              - Effect: Allow
                Action:
                  - lambda:AddPermission
                  - lambda:RemovePermission
                Resource: !GetAtt IngestFunction.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  S3NotificationConfiguratorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt S3NotificationConfiguratorRole.Arn
      Timeout: 60
      Code:
        ZipFile: |
          import json
          import boto3
          import urllib3

          http = urllib3.PoolManager()
          s3 = boto3.client("s3")
          lam = boto3.client("lambda")

          def send(event, context, status, data):
              response_body = json.dumps({
                  "Status": status,
                  "Reason": f"See CloudWatch Logs: {context.log_stream_name}",
                  "PhysicalResourceId": context.log_stream_name,
                  "StackId": event["StackId"],
                  "RequestId": event["RequestId"],
                  "LogicalResourceId": event["LogicalResourceId"],
                  "Data": data,
              })
              http.request("PUT", event["ResponseURL"], body=response_body, headers={"content-type": ""})

          def handler(event, context):
              try:
                  props = event["ResourceProperties"]
                  bucket = props["BucketName"]
                  function_arn = props["FunctionArn"]
                  suffix = props.get("Suffix", ".jpg")
                  statement_id = props.get("StatementId", "AllowS3Invoke")

                  if event["RequestType"] in ("Create", "Update"):
                      # Ensure Lambda permission exists (idempotent)
                      try:
                          lam.add_permission(
                              FunctionName=function_arn,
                              StatementId=statement_id,
                              Action="lambda:InvokeFunction",
                              Principal="s3.amazonaws.com",
                              SourceArn=f"arn:aws:s3:::{bucket}",
                          )
                      except lam.exceptions.ResourceConflictException:
                          pass

                      s3.put_bucket_notification_configuration(
                          Bucket=bucket,
                          NotificationConfiguration={
                              "LambdaFunctionConfigurations": [
                                  {
                                      "LambdaFunctionArn": function_arn,
                                      "Events": ["s3:ObjectCreated:*"],
                                      "Filter": {
                                          "Key": {
                                              "FilterRules": [
                                                  {"Name": "suffix", "Value": suffix}
                                              ]
                                          }
                                      },
                                  }
                              ]
                          },
                      )
                      send(event, context, "SUCCESS", {"Bucket": bucket, "Configured": True})
                      return

                  if event["RequestType"] == "Delete":
                      # Remove all notifications
                      s3.put_bucket_notification_configuration(
                          Bucket=bucket,
                          NotificationConfiguration={}
                      )
                      # Best-effort remove permission
                      try:
                          lam.remove_permission(FunctionName=function_arn, StatementId=statement_id)
                      except Exception:
                          pass

                      send(event, context, "SUCCESS", {"Bucket": bucket, "Deleted": True})
                      return

              except Exception as e:
                  send(event, context, "FAILED", {"Error": str(e)})

  ConfigureUploadBucketNotifications:
    Type: Custom::S3Notification
    DependsOn:
      - UploadBucket
      - IngestFunction
      - S3NotificationConfiguratorFunction
    Properties:
      ServiceToken: !GetAtt S3NotificationConfiguratorFunction.Arn
      BucketName: !Ref UploadBucket
      FunctionArn: !GetAtt IngestFunction.Arn
      Suffix: ".jpg"
      StatementId: "AllowS3InvokeFromUploadBucket"

Outputs:
  UploadBucketName:
    Description: Bucket where images are uploaded (.jpg triggers pipeline)
    Value: !Ref UploadBucket

  ProcessedBucketName:
    Description: Bucket where worker writes JSON results
    Value: !Ref ProcessedBucket

  TopicArn:
    Description: SNS topic used for fanout
    Value: !Ref FanoutTopic

  QueueUrl:
    Description: Primary worker SQS queue URL
    Value: !Ref WorkerQueue

  DLQUrl:
    Description: Dead-letter queue URL
    Value: !Ref WorkerDLQ

